transcription_service_url: "http://localhost:8000/transcribe/phonemes"
local_word_transcription_service_url: "http://localhost:8000/transcribe/words"
openai_word_transcription_service_url: "http://localhost:8000/transcribe/words/openai"
audio_folder: "audio_files"
preferred_word_transcription_service: "openai"